### ISSUE TITLE
trouble to extract mouse 'mm10' signatures through SigProfilerExtractorR

### ISSUE THREAD

**Issue by luolingqi** [AlexandrovLab/SigProfilerExtractorR#1]
Hi, I am new to the tool. I've tried to follow the 'easy to follow' instruction to install and run SigProfilerExtractorR on my VCF called against mouse (mm10). The simple R code that I used is:
 
**sigprofilerextractor("vcf", "output", data, minsigs=1, maxsigs=3, replicates=10, cpu=-1, refgen = 'mm10',genome_build="mm10", mtype=c("DINUC,ID,96"))**

But, the job_metadata file gives the following:

**-------Vital Parameters Used for the execution -------
input_type: vcf
inputdata: vcftest
startProcess: 1
endProcess: 3
totalIterations: 10
cpu: -1
hierarchy: False
refgen: GRCh38
genome_build: GRCh38
mtype: ['default'] 
init: random**

At least 2 things are out of expectation here: 1) I specified 'mm10', which I successfully installed I believe, but here says 'GRCh38'; 2) I specified the mutation types that I want, but it still works on the 'default' mtype.

I don't have this issue when I run SigProfilerMatrixGeneratorR/PlottingR. Can anybody help? Plus, not sure if it is due to the above I always get an error message as below:

**Time taken to collect 10 iterations for 1 signatures is 0.55 seconds
Optimization time is 0.01352691650390625 seconds
The reconstruction error is 0.0445, average process stability is 1.0 and 
the minimum process stability is 1.0 for 1 signatures

Extracting signature 2 for mutation type 96
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: index 1 is out of bounds for axis 1 with size 1

Detailed traceback: 
  File "/usr/local/lib/python3.6/site-packages/sigproextractor/sigpro.py", line 571, in sigProfilerExtractor
    gpu=gpu,)
  File "/usr/local/lib/python3.6/site-packages/sigproextractor/subroutines.py", line 984, in decipher_signatures
    results = parallel_runs(genomes=genomes, totalProcesses=totalProcesses, iterations=totalIterations,  n_cpu=cpu, verbose = False, resample=resample, seeds = seeds, init=init, normalization_cutoff=normalization_cutoff, gpu=gpu)
  File "/usr/local/lib/python3.6/site-packages/sigproextractor/subroutines.py", line 461, in parallel_runs
    result_list = pool.map(pool_nmf, seeds)
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value**

Thanks!

**Comment by luolingqi** [comment]
It is not an issue for python version "SigProfilerExtractor". :-)

**Comment by mishugeb** [comment]
Hi, we are currently working on a new release for the R version. I will let you know soon after we release the version.
