### ISSUE TITLE
 error in de_novo_fit_penalty like in issue #7 

### ISSUE THREAD

**Issue by frvirard** [AlexandrovLab/SigProfilerExtractorR#10]
Hi, I'm experiencing the same issue as #7 after having updated SigProfilerExtractor to v1.1.13
 Thanks for your help.

Best
Francois

**Comment by marcos-diazg** [comment]
Dear @frvirard,

Thanks for reaching out, and sorry for the issue you experienced. This has now been fixed in the most updated version of SigProfilerExtractorR v1.1.13. Please feel free to reopen the ticket if you are experiencing any additional problems.
