### ISSUE TITLE
unexpected keyword argument 'collapse_to_SBS96'

### ISSUE THREAD

**Issue by togasaki1220** [AlexandrovLab/SigProfilerExtractorR#13]
Hi,

I am trying to run the sigprofilerextractor() function as following:

sigprofilerextractor("vcf", 
                     output,
                     inputdata, 
                     "GRCh37"
                     #exome = TRUE #when WES turn TRUE
                     #minimum_signatures= 1,
                     #maximum_signatures= 25,
                     #nmf_replicates= 100,
                     #min_nmf_iterations = 10000,
                     #max_nmf_iterations =1000000,
                     #nmf_test_conv = 10000,
                     #nmf_tolerance = 0.00000001,
)

The type of inputdata file is vcf format.

I am having the following error when trying to run:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: sigProfilerExtractor() got an unexpected keyword argument 'collapse_to_SBS96'

**Comment by marcos-diazg** [comment]
Dear @togasaki1220,

I have just transferred your issue to the appropriate repo, as you are asking about the `sigprofilerextractor` function.

Could you please check that you have the latest versions of both the SigProfilerExtractorR R wrapper (v1.1.16) and the associated SigProfilerExtractor python package (v1.1.20)?

**Comment by marcos-diazg** [comment]
Please let us know and reopen the ticket if you are still having this issue after updating the versions of SigProfilerExtractorR and SigProfilerExtractor. Thanks for your interest!
