### ISSUE TITLE
cosmic v2 

### ISSUE THREAD

**Issue by ab08028** [AlexandrovLab/SigProfilerExtractorR#16]
Hi there, just wanted to let you know what when trying to run sigprofilerextractorR using cosmic v2, the reference file is not found: 
/opt/anaconda3/lib/python3.8/site-packages/SigProfilerAssignment/data/Reference_Signatures/GRCh37/COSMIC_**v2.0**_SBS_GRCh37.txt

because that file is actually named "COSMIC_**v2**_SBS_GRCh37.txt" 

Renaming that file to be "v2.0" instead of "v2" made the program run as expected

I imagine this would also be a problem for the "v1" labeled files too 

Cheers,
~ Annabel

**Comment by marcos-diazg** [comment]
Dear Annabel,

Thanks so much for your feedback! Could you please let us know the exact commands you run to get this error? That would be helpful to understand a bit better where this is coming from and if this is specific only to the R implementation.

Thanks in advance. Best,

Marcos

**Comment by ab08028** [comment]
Absolutely! I'm using version 1.1.16 of SigProfilerExtractorR
and the command was: 

`
sigprofilerextractor(input_type = "table", 
                     paste0(spe_outdir,"perFamily/"), 
                     input_data=paste0(inputdir,"AllSpectra.FormattedForSigProfilerExtractor.PERFAMILY.txt"), 
                     reference_genome="GRCh38",
                     minimum_signatures=1,
                     maximum_signatures=3,
                     nmf_replicates=100,
                     cosmic_version = 2)
`
                     
and the error was:
` /opt/anaconda3/lib/python3.8/site-packages/SigProfilerAssignment/data/Reference_Signatures/GRCh37/COSMIC_v2.0_SBS_GRCh37.txt file not found.  `

It looks like there's also a slight incompatibility that I'm specifying GRCh38 as the reference genome, but 37 is being called (I'm guessing that's the only one available for COSMIC v2?) 

Thanks so much for looking into it! :)

**Comment by mdbarnesUCSD** [comment]
Hi @ab08028,

Please update your installation of SigProfilerExtractorR and try again. The recent update should resolve this issue. Thanks!
