### ISSUE TITLE
Decomposition function does not decomposite the de novo signatures to cosmic global signatures.

### ISSUE THREAD

**Issue by marshelma** [AlexandrovLab/SigProfilerExtractorR#2]
Running the function 'sigprofilerextractor', the suggested solution is 6 de novo signature

  | Stability (Avg Silhouette) | Minimum Stability | Matrix Frobenius% | Mean Sample L1% | Maximum Sample L1% | Mean Sample L2% | Maximum Sample L2% | Significant Decrease of L2 | Mean Sample KL | Maximum Sample KL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 1 | 1 | 57.73% | 51.11% | 147.37% | 50.98% | 145.87% | TRUE | 0.2305 | 2.0591
2 | 1 | 1 | 26.30% | 28.52% | 127.72% | 25.53% | 95.14% | TRUE | 0.0984 | 1.5946
3 | 0.99 | 0.98 | 20.30% | 24.68% | 128.24% | 20.89% | 92.43% | FALSE | 0.0834 | 1.561
4 | 0.94 | 0.9 | 16.82% | 21.43% | 121.02% | 16.11% | 96.94% | TRUE | 0.0703 | 1.3847
5 | 0.8 | 0.12 | 15.70% | 18.83% | 83.93% | 13.67% | 62.86% | FALSE | 0.0542 | 0.6204
6* | 0.88 | 0.32 | 14.62% | 16.52% | 49.01% | 11.80% | 33.24% | TRUE | 0.0425 | 0.2881
7 | 0.87 | 0.3 | 11.86% | 14.77% | 50.16% | 10.35% | 31.06% | FALSE | 0.0348 | 0.3028
8 | 0.68 | -0.49 | 11.95% | 14.49% | 49.32% | 9.97% | 34.42% | FALSE | 0.0333 | 0.3079
9 | 0.78 | -0.03 | 9.32% | 12.23% | 26.99% | 8.27% | 27.23% | TRUE | 0.0252 | 0.1273
10 | 0.6 | -0.02 | 9.84% | 12.23% | 27.57% | 8.50% | 26.69% | FALSE | 0.0238 | 0.1286

However, in the decomposition folder, all samples are assigned to 8 signatures (signature A~ F, SBS1, SBS5). Here is the first a few line from the file 'Decomposed_Solution_Signatures_SBS96.txt'

MutationsType | SBS1 | SBS5 | Signature A | Signature B | Signature C | Signature D | Signature E | Signature F
-- | -- | -- | -- | -- | -- | -- | -- | --
A[C>A]A | 0.000886 | 0.011998 | 0.001695 | 0.000153 | 0 | 0.000733 | 9.86E-05 | 0.002613
A[C>A]C | 0.00228 | 0.009438 | 0.002864 | 0.003437 | 0.00096 | 0.004188 | 0.000455 | 1.77E-06
A[C>A]G | 0.000177 | 0.00185 | 0.000913 | 0.000123 | 0 | 0.000608 | 0 | 1.93E-06
A[C>A]T | 0.00128 | 0.006609 | 0.012232 | 0.019794 | 0 | 0.011603 | 0 | 1.31E-06
C[C>A]A | 0.00186 | 0.010098 | 0.002824 | 0.002846 | 0.002816 | 0.016223 | 1.9E-05 | 0.024425
C[C>A]C | 0.00122 | 0.005699 | 0.001623 | 0.002203 | 0.000484 | 0.027418 | 0.000285 | 0.000546
C[C>A]G | 0.000115 | 0.00172 | 0.001503 | 0.000929 | 0.000289 | 0.00955 | 0 | 1.53E-06
C[C>A]T | 0.00114 | 0.010098 | 0.015617 | 0.059091 | 0.000421 | 0.129235 | 0.001499 | 0.024569

The file 'comparison_with_global_ID_signatures.csv' shows

De novo extracted | Global NMF Signatures | L1   Error % | L2   Error % | Cosine   Similarity
-- | -- | -- | -- | --
Signature 96-A | Signature 96-A | 0 | 0 | 1
Signature 96-B | Signature 96-B | 0 | 0 | 1
Signature 96-C | Signature 96-C | 0 | 0 | 1
Signature 96-D | Signature 96-D | 0 | 0 | 1
Signature 96-E | Signature 96-E | 0 | 0 | 1
Signature 96-F | Signature 96-F | 0 | 0 | 1

Why the de novo signatures are not deomposited to Cosmic SBS signatures?

**Comment by mishugeb** [comment]
Hi, 
I am very sorry that I could not reach you earlier. 

There are two reasons which will report new signatures not decomposing them into COSMIC signatures. Firstly, if the linear combination of the COSMIC signatures is less than cosine similarity 0.8 compared to the original de-novo signature; Secondly, if the original de-novo signature decomposes into more than four COSMIC signature. To see what actually happened, please check the "decomposition_logfile.txt" in the "Suggested_Solution/Decomposed_Solution" in your result. 

Thanks, 
Mishu
