### ISSUE TITLE
Error in refgen while using SigProfilerExtractorR

### ISSUE THREAD

**Issue by mathbioGVN** [AlexandrovLab/SigProfilerExtractorR#3]
Hi all,

I am trying to use the function as the following:

sigprofilerextractor("table", output="output",filteredT , refgen = "GRCh37",
                     genome_build = "GRCh37", minsigs = 1, maxsigs = 3,
                     replicates = 5, mtype = c("96,DINUCS,ID"), init = "random",
                    exome = F, cpu = -1)

I received this error below;

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: sigProfilerExtractor() got an unexpected keyword argument 'refgen'

BTW, I installed reference genome for human by using install("GRCh37", rsync=FALSE, bash=TRUE)

after about 40 minutes wait time, the installation was successful.

**Comment by rxy712** [comment]
I have the same issue. What is the solution? Thanks a lot!

**Comment by rptashkin** [comment]
this issue is in the call to sigpro$sigProfilerExtractor(). This function takes different arguments than sigProfilerExtractor()

**Comment by rxy712** [comment]
Thank you so much for your kind help!
