### ISSUE TITLE
simultaneous analysis of genomes and exomes

### ISSUE THREAD

**Issue by MariaCartolano** [AlexandrovLab/SigProfilerExtractorR#4]
Hello,

I would like to analyze in the same batch WGS and WES data. Is it possible to do this using the SigProfilerExtractor?
How is exome normalisation performed?

Thank you in advance for your help.
Maria

**Comment by mishugeb** [comment]
Hi Maria,
Sorry for the delayed response as I did not get any notification of this issue in the repository.
If you use "exome=TRUE", that will analyze the WES data.
If you use "exome=FALSE", that will analyze the WGS data.

Thanks,
Mishu
