### ISSUE TITLE
no cosmic decomposition for strand bias

### ISSUE THREAD

**Issue by frvirard** [AlexandrovLab/SigProfilerExtractorR#6]
Hi all,
I have an issue with the cosmic decompostion step of suggested signature.
While the decomposition works well with the SBS96 matrix, it doesn't seems to operate on strand bias matrix.
I used the SBS384 matrix generated by SigProfilerMatrixGeneratorR, but I didn't get any mapping to COSMIC signatures.

Here's the De_Novo_map_to_COSMIC_SBS384.csv file :
[De_Novo_map_to_COSMIC_SBS384.csv](https://github.com/AlexandrovLab/SigProfilerExtractorR/files/7234885/De_Novo_map_to_COSMIC_SBS384.csv)

and the log file :
[Cosmic_SBS384_Decomposition_Log.txt](https://github.com/AlexandrovLab/SigProfilerExtractorR/files/7234898/Cosmic_SBS384_Decomposition_Log.txt)

thanks for your help

**Comment by lalexandrov1018** [comment]
Thank you for reporting this issue! 

We have actually stopped using SBS384 as there are too few bidirectional mutations. You can use extraction based on SBS288 which includes transcribed, untranscribed, and intergenic (mutations in bidirectional transcription are split equally between transcribed and untranscribed). You should get clean mapping of SBS288 to the COSMIC signatures.

**Comment by frvirard** [comment]
Thank you for your reply.
I was indeed able to do the mapping with SBS288 matrix.
However, I not sure the mapping takes into account the strand bias as I have nearly the same contribution of SBS5 and SBS16 in my dataset while it seems to me that I have strong strand bias in T>C in my SBS96E signature.
![SBS compare](https://user-images.githubusercontent.com/74251513/135571011-52bcd219-0960-46c8-b47c-604087641263.jpg)

**Comment by frvirard** [comment]
Is it possible to use the decomposition function with a custom database for this purpose ?
I created a custom database from SBS288 profiles downloaded on COSMIC's website but it doesn't seem to work.

**Comment by lalexandrov1018** [comment]
SigProfilerExtractor supports decomposition from a custom database. @mishugeb should be able to give you more details as he implemented that function.

**Comment by marcos-diazg** [comment]
Dear @frvirard,

Sorry for the late reply. You can use the decomposition function with a custom database. You need to provide the path for this dataset in the `signature_database` parameter of the `decompose` function. Just make sure that the format is similar to the one used by the [COSMIC reference signatures](https://cancer.sanger.ac.uk/signatures/downloads/).

I hope this helps, and please let me know if you have any other issues.

Best,

Marcos

**Comment by marcos-diazg** [comment]
Please reopen the ticket if you are still experiencing any issues. Thanks for your interest!
