### ISSUE TITLE
ModuleNotFoundError: No module named 'SigProfilerExtractor'

### ISSUE THREAD

**Issue by tdelhomme** [AlexandrovLab/SigProfilerExtractorR#8]
This is not an issue _per se_ but I think someone else would probably look at here to find a solution.
It seems there is a typo in the readme:
```
pip install sigproextractor
```
this should be:
```
pip install SigProfilerExtractor
```
otherwise then there is an error in R, python does not find the correct package.

Thanks!

**Comment by marcos-diazg** [comment]
This was indeed a typo, and it's corrected now. Thanks so much for pointing this out!
