### ISSUE TITLE
No NAMESPACE file 

### ISSUE THREAD

**Issue by pinunQ** [AlexandrovLab/SigProfilerExtractorR#9]
Hi, 
The package supposed to have a NAMESPACE file as during the installation it throws an error that NAMESPACE file is required.

I tried to install with the simple command but the error comes every time I do it.

`devtools::install_github("AlexandrovLab/SigProfilerExtractorR")
Downloading GitHub repo AlexandrovLab/SigProfilerExtractorR@master
from URL https://api.github.com/repos/AlexandrovLab/SigProfilerExtractorR/zipball/master
Installing SigProfilerExtractorR
'/data/users/prakha/Main/envs/RP/lib/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpq3kdOM/devtoolsc4fe179727219/AlexandrovLab-SigProfilerExtractorR-01dca1c'  \
  --library='/data/users/prakha/Main/envs/RP/lib/R/library' --install-tests

* installing *source* package ‘SigProfilerExtractorR’ ...
ERROR: a 'NAMESPACE' file is required
* removing ‘/data/users/prakha/Main/envs/RP/lib/R/library/SigProfilerExtractorR’
Installation failed: Command failed (1)`

Can you help with this error?

**Comment by marcos-diazg** [comment]
Dear @pinunQ,

Thanks for your interest! A default NAMESPACE file should be created by the `install_github` command. I have tried to reproduce your issue, but I was not able. The installation worked fine on my end. Could you please check the R and devtools versions you are using? I would suggest using a dedicated conda environment where you can install the dependencies needed for SigProfilerExtractorR.

Also, please remember that you need to install reticulate in R, and also the base SigProfilerExtractor python package through pip before proceeding to the SigProfilerExtractorR installation.

I hope this helps, and please let me know if you are still having any issues.

**Comment by pinunQ** [comment]
Hello,

I appreciate your quick response on my problem, the problem is resolved after following the Python path to my python to my path of SigProfilerExtractor. then it installed it.
